[tool.poetry]
name = "fastapi-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.115.12"
prisma = "^0.15.0"
langchain = "^0.3.22"
uvicorn = "^0.34.0"
pydantic = "^2.11.1"
python-dotenv = "^1.1.0"
openai = "^1.70.0"
langchain-community = "^0.3.20"
langchain-openai = "^0.3.11"
tiktoken = "^0.9.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
